name: time_series_generator
description: a grpc microservice that generates tones
publish_to: none

environment:
  sdk: '^3.0.0'

dependencies:
  async: ^2.2.0
  grpc: ^3.1.0
  protobuf: ^2.1.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  lints: ^2.0.0
